### ISSUE TITLE
test whether the protocol seems sufficient

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/lost-jse-issues#1]
Can each of the two of you populate three papers and meta-data for those papers (Sarah, volume 7; Siyi, volume 8) and add them into the mix?

The goal here is to see if we can standardize a process and double check that all of the relevant info is being collected.

If you can look out for anything weird or unusual that would be great.

This issue will be closed when the two of you have reviewed the others' additions.

**Comment by sedelson31** [comment]
I added the metadata for the papers in volume 7 - in terms of generating the PDF, did you want us to just save the webpage as a PDF?

**Comment by nicholasjhorton** [comment]
Yes, please!

**Comment by nicholasjhorton** [comment]
@sedelson31 thanks for your work: this looks great. Note that I moved the two folders into one (see https://www.dropbox.com/s/xa59fl2fe5ho3bi/Screen%20Shot%202021-11-02%20at%202.15.49%20PM.png?dl=0)

Can you please pull and confirm that you are able to see these changes?

@sili22 any updates on your work with the protocol?

**Comment by sedelson31** [comment]
@nicholasjhorton yes - I can see these changes

**Comment by sili22** [comment]
I added the matadata, the pdfs, and the htmls for volume 8!

**Comment by nicholasjhorton** [comment]
The initial files look great: I'm closing this now.
