### ISSUE TITLE
figure out how to incorporate the additional figures into the metadata and/or the pdf

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/lost-jse-issues#12]
In issue #8 @sedelson31 and @sili22 will be working to retrieve any figures, equations, or other downloadable bits that aren't fully included in the html and pdf files.

How do we deal with these?

We need to think about the metadata (perhaps list these in the note section?  e.g., for Anderson-Cook 7(3) "four supplementary figures as pdf"

We need to think about whether to include the supplementary figures in the main pdf file.

Status: to think and discuss at a future meeting.

**Comment by sili22** [comment]
I think we need to mention this in the metadata. It will be important to do this in a consistent way. For example, for Anderson-Cook 7(3) "four supplementary figures as pdf" should appear in the note column. 
We can add an r markdown file which describes how many figures there are for which papers.

**Comment by sili22** [comment]
this will be implemented in #8 .
