### ISSUE TITLE
missing papers

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/lost-jse-issues#16]
- https://github.com/nicholasjhorton/lost-jse-issues/blob/main/papers/boyle_7_1.html  (no boyle.pdf)
- https://github.com/nicholasjhorton/lost-jse-issues/blob/main/papers/tryfos_7_1.html (no tryfos.pdf)
- https://github.com/nicholasjhorton/lost-jse-issues/blob/main/papers/abstracts_7_3.pdf (Popper Schafer pdf missing?)

**Comment by nicholasjhorton** [comment]
I'm not seeing the following three pdf's (and no html or pdf for Popper Shaffer): can @sedelson31 and/or @sili22 please investigate?

**Comment by sedelson31** [comment]
The html and pdf for Popper Shaffer was in the "sample_taylor_francis_paper" folder so I just moved it. Will add the other 2 pdfs.

**Comment by sedelson31** [comment]
They have been added.

**Comment by nicholasjhorton** [comment]
Thanks!
