### ISSUE TITLE
randomly audit aspects of volume 7 and volume 8

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/lost-jse-issues#3]
To confirm that things are all sussed, we want to have a second set of eyes on the curation that was done by @sili22 for volume 8 and by @sedelson31 for volume 7.

Can each of you pick 3 papers from the other's work and just double check that everything looks okay?  

Please comment in this issue if you see anything questionable as it may lead us to do additional data audits.

**Comment by sedelson31** [comment]
I did this for volume 8 - everything looks fine.

**Comment by sili22** [comment]
Did this for volume 7 and everything looks good!

**Comment by nicholasjhorton** [comment]
Thanks to you both!
