### ISSUE TITLE
complete the curation process for all papers (not just articles)

### ISSUE THREAD

**Issue by nicholasjhorton** [nicholasjhorton/lost-jse-issues#6]
Please include all of the wayback machine headers in these new papers so that we can ensure that they are saved on Github.

Later we can elide these (see #5)

**Comment by sedelson31** [comment]
Completed for volume 7

**Comment by sili22** [comment]
completed for volume 8

**Comment by nicholasjhorton** [comment]
This looks great. Next step: https://github.com/nicholasjhorton/lost-jse-issues/issues/3

**Comment by nicholasjhorton** [comment]
@sili22 @sedelson31 kudos again for your work on this front: the lost issues are now available!

See for example: https://www.tandfonline.com/toc/ujse20/7/3?nav=tocList

I'm still working on the AE information (which is most helpful).

**Comment by sedelson31** [comment]
Great! Hope everyone has had a good summer.
